version: 2.1
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
      - store_test_results:
         path: ~/app/reports/mocha
      - store_artifacts:
          path: ~/app/reports/mocha
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run lint-ci
      - store_test_results:
          path: ~/app/reports/eslint
      - store_artifacts:
          path: ~/app/reports/eslint
workflows:
  version: 2
  test:
    jobs:
      - "build"
      - "test":
          requires: 
            - build
      - "lint":
          requires: 
            - build
